//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobSales.DroidUI
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxHttpSource = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int Address = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int ErrorText1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int ErrorText2 = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Name = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int autocomplete = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int btnCancel = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int btnSelect = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int button_frame = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int dialog_view = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int titles_fragment = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int toast_layout_error_root = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int txtfield = 2130968579;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dashboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int inserimentoodv = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int inserimentoreso = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem_Customer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SplashScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_frag = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ToastLayout_Error = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
